@extends('auto_posts.super_admin.layouts.app')
@push('title'){{ $title }}@endpush
@section('content')
<div class="section-title"><h2 class="title">{{ $title }}</h2></div>
<div class="settings-page-area">@include('auto_posts.super_admin.setting.partials.general-sidebar')<div class="settings-page-right"><div class="section-wrap"><div class="section-inner-title"><h3 class="title">{{ __('AI Chatbot') }}</h3></div><div class="primary-form"><form id="ai-settings-form" class="ajax" action="{{ route('super_admin.setting.ai-settings.update') }}" method="POST" data-handler="settingCommonHandler">@csrf
@php($selectedProvider = getOption('ai_provider', config('ai.default_provider', 'openai')))
@php($selectedConfig = $providers[$selectedProvider] ?? reset($providers))
@php($selectedModel = getOption('ai_model', getOption($selectedProvider . '_model', $selectedConfig['default_model'] ?? '')))
<div class="row gy-4"><div class="col-xl-4 col-lg-5 col-md-6"><div class="form-group"><label class="form-label" for="openai_ai_status">{{ __('Chatbot status') }} <span class="required">*</span></label><select name="openai_ai_status" id="openai_ai_status" class="select form-control wide"><option value="1" @selected(getOption('openai_ai_status', 1) == 1)>{{ __('Active') }}</option><option value="0" @selected(getOption('openai_ai_status', 1) == 0)>{{ __('Inactive') }}</option></select><small class="text-muted">{{ __('Enable or disable the AI chatbot for users.') }}</small></div></div><div class="col-xl-4 col-lg-7 col-md-6"><div class="form-group"><label class="form-label" for="ai_provider">{{ __('AI provider') }} <span class="required">*</span></label><select name="ai_provider" id="ai_provider" class="select form-control wide">@foreach($providers as $key => $provider)<option value="{{ $key }}" @selected($selectedProvider === $key)>{{ $provider['label'] }}</option>@endforeach</select><small class="text-muted">{{ __('Choose which provider powers the chatbot.') }}</small></div></div><div class="col-xl-4 col-lg-6 col-md-6"><div class="form-group"><label class="form-label" for="ai_model">{{ __('Chat model') }} <span class="required">*</span></label><select name="ai_model" id="ai_model" class="select form-control wide"></select><small class="text-muted">{{ __('The selected provider model will be used.') }}</small></div></div><div class="col-xl-8 col-lg-6 col-md-6"><div class="form-group"><label class="form-label" for="provider_api_key">{{ __('Provider API key') }} <span class="required">*</span></label><input type="password" name="provider_api_key" id="provider_api_key" class="form-control" value="{{ getOption($selectedConfig['api_key_option'], '') }}" placeholder="Paste selected provider API key" autocomplete="new-password"><small id="provider-help" class="text-muted">{{ __('The key stays on your server and is never shown to chatbot users.') }}</small></div></div><div class="col-xl-4 col-lg-6 col-md-6"><div class="form-group"><label class="form-label" for="openai_max_tokens">{{ __('Max tokens') }} <span class="required">*</span></label><input type="number" id="openai_max_tokens" name="openai_max_tokens" value="{{ getOption('openai_max_tokens', config('ai.openai_default_max_tokens', 1000)) }}" class="form-control" min="100" max="4096"></div></div></div></form></div><div class="btn-list"><button type="submit" form="ai-settings-form" class="primary-btn">{{ __('Save chatbot settings') }}</button></div></div></div></div>
@push('script')<script>document.addEventListener('DOMContentLoaded',function(){const providers=@json($providers);const provider=document.getElementById('ai_provider');const model=document.getElementById('ai_model');const selected=@json($selectedModel);const keyInput=document.getElementById('provider_api_key');function update(){const p=providers[provider.value]||{};model.innerHTML='';(p.models||[]).forEach(function(m){const o=document.createElement('option');o.value=m;o.textContent=m;if(m===(provider.value==='{{ $selectedProvider }}'?selected:p.default_model))o.selected=true;model.appendChild(o)});keyInput.value='';keyInput.placeholder='Paste '+(p.label||'provider')+' API key'}provider.addEventListener('change',update);update();});</script>@endpush
@endsection
