<form class="ajax reset costing-form" action="{{ $costing ? route('admin.garments.costings.update', $costing->id) : route('admin.garments.costings.store') }}" method="post" data-handler="commonResponseWithPageLoad">
    @csrf
    @if($costing) @method('put') @endif
    <div class="modal-body zModalTwo-body">
        <div class="d-flex justify-content-between align-items-center border-bottom pb-3"><div><h4 class="fs-20 fw-600 lh-28 text-1b1c17 mb-1">{{ $costing ? __('Edit Costing') : __('Add Costing') }}</h4><p class="buyer-modal-subtitle mb-0">{{ __('Calculate CM, total cost, FOB and expected profit per order.') }}</p></div><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div>
        <div class="primary-form mt-4">
            <div class="costing-form-section"><h5 class="costing-form-section-title"><i class="fa-solid fa-file-invoice"></i>{{ __('Order Reference') }}</h5><div class="row gy-3"><div class="col-md-8"><div class="form-group"><label class="form-label">{{ __('Order') }} <span class="required">*</span></label><select class="form-control" name="order_id" required><option value="">{{ __('Select Order') }}</option>@foreach($orders as $orderOption)<option value="{{ $orderOption->id }}" @selected(old('order_id', $costing?->order_id) == $orderOption->id)>{{ $orderOption->order_number }} | {{ $orderOption->style?->style_code }} - {{ $orderOption->buyer?->company_name }}</option>@endforeach</select></div></div><div class="col-md-4"><div class="form-group"><label class="form-label">{{ __('Status') }} <span class="required">*</span></label><select class="form-control" name="status" required>@foreach(garmentCostingStatuses() as $statusValue => $statusData)<option value="{{ $statusValue }}" @selected(old('status', $costing?->status ?? GARMENT_COSTING_STATUS_DRAFT) == $statusValue)>{{ __($statusData[0]) }}</option>@endforeach</select></div></div></div></div>

            <div class="costing-form-section"><h5 class="costing-form-section-title"><i class="fa-solid fa-coins"></i>{{ __('Cost Components') }}</h5><div class="row gy-3">
                @foreach(['fabric_cost' => 'Fabric Cost', 'trims_cost' => 'Trims Cost', 'accessories_cost' => 'Accessories Cost', 'cm_cost' => 'CM Cost', 'washing_cost' => 'Washing Cost', 'printing_cost' => 'Printing Cost', 'embroidery_cost' => 'Embroidery Cost', 'overhead_cost' => 'Overhead Cost', 'other_cost' => 'Other Cost'] as $field => $label)
                    <div class="col-md-4"><div class="form-group"><label class="form-label">{{ __($label) }}</label><input type="number" min="0" step="0.0001" class="form-control costing-component" name="{{ $field }}" value="{{ old($field, $costing?->$field ?? 0) }}" data-costing-field="{{ $field }}"></div></div>
                @endforeach
            </div></div>

            <div class="costing-summary"><div class="costing-summary-item"><span class="costing-summary-label">{{ __('Total Cost') }}</span><strong class="costing-summary-value" id="costing-total-display">0.0000</strong></div><div class="costing-summary-item"><label class="costing-summary-label" for="costing-fob-input">{{ __('FOB Price') }}</label><input type="number" min="0" step="0.0001" class="form-control" name="fob_price" id="costing-fob-input" value="{{ old('fob_price', $costing?->fob_price ?? 0) }}" required></div><div class="costing-summary-item"><span class="costing-summary-label">{{ __('Profit') }}</span><strong class="costing-summary-value" id="costing-profit-display">0.0000</strong></div><div class="costing-summary-item"><span class="costing-summary-label">{{ __('Margin') }}</span><strong class="costing-summary-value" id="costing-margin-display">0.00%</strong></div></div>

            <div class="costing-form-section mt-3"><h5 class="costing-form-section-title"><i class="fa-solid fa-note-sticky"></i>{{ __('Notes') }}</h5><textarea class="form-control" name="notes" rows="3" placeholder="{{ __('Add costing assumptions or remarks') }}">{{ old('notes', $costing?->notes) }}</textarea></div>
        </div>
        <div class="costing-modal-footer"><button type="button" class="primary-btn" data-bs-dismiss="modal">{{ __('Cancel') }}</button><button type="submit" class="primary-btn"><i class="fa-solid fa-check me-2"></i>{{ $costing ? __('Update Costing') : __('Save Costing') }}</button></div>
    </div>
</form>
