@extends('auto_posts.admin.layouts.admin')
@push('title') {{ $title }} @endpush
@section('content')
<div class="section-title"><h2 class="title">{{ __($title) }}</h2><button class="primary-btn" data-bs-toggle="modal" data-bs-target="#add-accounting-modal"><i class="fa fa-plus me-2"></i>{{ __('Add Entry') }}</button></div>
<div class="settings-page-area"><div class="settings-page-right"><div class="section-wrap"><div class="table-waraper"><input type="hidden" id="accounting-route" value="{{ route('admin.garments.accounting.index') }}"><table class="display primary-table dataTable dtr-inline" id="garmentAccountingDataTable"><thead><tr><th class="keep-show">SL</th><th>Order</th><th>Type</th><th>Account</th><th>Debit</th><th>Credit</th><th>Status</th><th class="keep-show">Action</th></tr></thead><tbody></tbody></table></div></div></div></div>
<div class="modal fade zModalTwo" id="add-accounting-modal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable"><div class="modal-content zModalTwo-content">@include('admin.garments.accounting.form',['entry'=>null,'orders'=>$orders])</div></div></div><div class="modal fade zModalTwo" id="edit-accounting-modal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content zModalTwo-content"></div></div></div>
@endsection
@push('style')<style>
#add-accounting-modal .modal-dialog,#edit-accounting-modal .modal-dialog,#add-incentive-modal .modal-dialog,#edit-incentive-modal .modal-dialog{max-width:980px;height:calc(100% - 2rem);min-height:0}#add-accounting-modal .modal-content,#edit-accounting-modal .modal-content,#add-incentive-modal .modal-content,#edit-incentive-modal .modal-content{height:100%;max-height:100%;overflow:hidden}#add-accounting-modal form,#edit-accounting-modal form,#add-incentive-modal form,#edit-incentive-modal form{display:flex;flex-direction:column;height:100%}#add-accounting-modal .modal-body,#edit-accounting-modal .modal-body,#add-incentive-modal .modal-body,#edit-incentive-modal .modal-body{flex:1;min-height:0;overflow-y:auto;padding:30px}.modal-form-header{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:24px}.modal-form-header h4{font-size:20px;font-weight:500;line-height:28px;color:#1b1c17;margin:0 0 4px}.modal-form-header p{font-size:13px;color:#808080;margin:0}.accounting-form-section,.incentive-form-section{border:1px solid #eee8e5;border-radius:10px;background:#fff;padding:20px}.accounting-form-section+.accounting-form-section,.incentive-form-section+.incentive-form-section{margin-top:16px}.accounting-section-title,.incentive-section-title{display:flex;align-items:center;gap:12px;border-bottom:1px solid #f0ecea;padding-bottom:14px;margin-bottom:18px}.accounting-section-title>span,.incentive-section-title>span{width:36px;height:36px;display:inline-flex;align-items:center;justify-content:center;border-radius:8px;color:#ff4f02;background:#fff2ec}.accounting-section-title h5,.incentive-section-title h5{font-size:15px;font-weight:600;color:#1b1c17;margin:0 0 3px}.accounting-section-title p,.incentive-section-title p{font-size:12px;color:#808080;margin:0}.accounting-form .form-group,.incentive-form .form-group{margin-bottom:0}.accounting-form .form-control,.incentive-form .form-control{min-height:44px}
</style>@endpush
@push('script')<script>$(function(){var t=$('#garmentAccountingDataTable').DataTable({pageLength:10,ordering:false,serverSide:true,processing:true,responsive:true,dom:'t',ajax:$('#accounting-route').val(),columns:[{data:'sl'},{data:'order_number'},{data:'type_display'},{data:'account_name'},{data:'debit'},{data:'credit'},{data:'status'},{data:'action'}],columnDefs:[{targets:'keep-show',className:'all'}]});});</script>@endpush
