<form class="ajax reset grn-form" action="{{ $grn ? route('admin.garments.grns.update', $grn->id) : route('admin.garments.grns.store') }}" method="post" data-handler="commonResponseWithPageLoad">
    @csrf
    @if($grn) @method('put') @endif
    <div class="modal-body zModalTwo-body">
        <div class="d-flex justify-content-between align-items-center border-bottom pb-3"><div><h4 class="fs-20 fw-600 lh-28 text-1b1c17 mb-1">{{ $grn ? __('Edit GRN') : __('Add Goods Received Note') }}</h4><p class="buyer-modal-subtitle mb-0">{{ __('Record accepted material receipt and update store stock.') }}</p></div><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div>
        <div class="primary-form mt-4">
            <div class="grn-form-section"><h5 class="grn-form-section-title"><i class="fa-solid fa-receipt"></i>{{ __('Receipt Details') }}</h5><div class="row gy-3">
                <div class="col-md-4"><div class="form-group"><label class="form-label">{{ __('GRN Number') }} <span class="required">*</span></label><input type="text" class="form-control" name="grn_number" value="{{ old('grn_number', $grn?->grn_number) }}" placeholder="{{ __('e.g. GRN-2026-001') }}" required></div></div>
                <div class="col-md-4"><div class="form-group"><label class="form-label">{{ __('Material') }} <span class="required">*</span></label><select class="form-control" name="material_id" required><option value="">{{ __('Select Material') }}</option>@foreach($materials as $materialOption)<option value="{{ $materialOption->id }}" @selected(old('material_id', $grn?->material_id) == $materialOption->id)>{{ $materialOption->item_code }} - {{ $materialOption->item_name }}</option>@endforeach</select></div></div>
                <div class="col-md-4"><div class="form-group"><label class="form-label">{{ __('Received Date') }} <span class="required">*</span></label><input type="date" class="form-control" name="received_date" value="{{ old('received_date', $grn?->received_date?->format('Y-m-d') ?? now()->format('Y-m-d')) }}" required></div></div>
                <div class="col-md-6"><div class="form-group"><label class="form-label">{{ __('Supplier Name') }} <span class="required">*</span></label><input type="text" class="form-control" name="supplier_name" value="{{ old('supplier_name', $grn?->supplier_name) }}" placeholder="{{ __('Enter supplier name') }}" required></div></div>
                <div class="col-md-6"><div class="form-group"><label class="form-label">{{ __('Purchase Reference') }}</label><input type="text" class="form-control" name="purchase_reference" value="{{ old('purchase_reference', $grn?->purchase_reference) }}" placeholder="{{ __('PO or invoice reference') }}"></div></div>
            </div></div>

            <div class="grn-form-section"><h5 class="grn-form-section-title"><i class="fa-solid fa-scale-balanced"></i>{{ __('Quantity & Cost') }}</h5><div class="row gy-3">
                <div class="col-md-3"><div class="form-group"><label class="form-label">{{ __('Ordered Qty') }}</label><input type="number" min="0" step="0.0001" class="form-control" name="ordered_quantity" value="{{ old('ordered_quantity', $grn?->ordered_quantity ?? 0) }}"></div></div>
                <div class="col-md-3"><div class="form-group"><label class="form-label">{{ __('Received Qty') }} <span class="required">*</span></label><input type="number" min="0.0001" step="0.0001" class="form-control grn-quantity" id="grn-received-quantity" name="received_quantity" value="{{ old('received_quantity', $grn?->received_quantity ?? 0) }}" required></div></div>
                <div class="col-md-3"><div class="form-group"><label class="form-label">{{ __('Rejected Qty') }}</label><input type="number" min="0" step="0.0001" class="form-control grn-quantity" id="grn-rejected-quantity" name="rejected_quantity" value="{{ old('rejected_quantity', $grn?->rejected_quantity ?? 0) }}"></div></div>
                <div class="col-md-3"><div class="form-group"><label class="form-label">{{ __('Unit Cost') }}</label><input type="number" min="0" step="0.0001" class="form-control" name="unit_cost" value="{{ old('unit_cost', $grn?->unit_cost ?? 0) }}"></div></div>
            </div><div class="grn-summary">{{ __('Accepted quantity to stock:') }} <strong id="grn-accepted-display">0.0000</strong></div></div>

            <div class="grn-form-section"><h5 class="grn-form-section-title"><i class="fa-solid fa-note-sticky"></i>{{ __('Status & Notes') }}</h5><div class="row gy-3"><div class="col-md-4"><div class="form-group"><label class="form-label">{{ __('Status') }} <span class="required">*</span></label><select class="form-control" name="status" required>@foreach(garmentGrnStatuses() as $statusValue => $statusData)<option value="{{ $statusValue }}" @selected(old('status', $grn?->status ?? GARMENT_GRN_STATUS_RECEIVED) == $statusValue)>{{ __($statusData[0]) }}</option>@endforeach</select></div></div><div class="col-md-8"><div class="form-group"><label class="form-label">{{ __('Notes') }}</label><textarea class="form-control" name="notes" rows="3" placeholder="{{ __('Add receiving or quality notes') }}">{{ old('notes', $grn?->notes) }}</textarea></div></div></div></div>
        </div>
        <div class="grn-modal-footer"><button type="button" class="primary-btn" data-bs-dismiss="modal">{{ __('Cancel') }}</button><button type="submit" class="primary-btn"><i class="fa-solid fa-check me-2"></i>{{ $grn ? __('Update GRN') : __('Save GRN') }}</button></div>
    </div>
</form>
