<form class="ajax reset" action="{{ $profitLoss ? route('admin.garments.profit-loss.update',$profitLoss->id) : route('admin.garments.profit-loss.store') }}" method="post" data-handler="commonResponseWithPageLoad">
    @csrf
    @if($profitLoss) @method('put') @endif
    <div class="modal-body zModalTwo-body">
        <div class="modal-form-header"><div><h4>{{ $profitLoss ? __('Edit Order Profit & Loss') : __('Add Order Profit & Loss') }}</h4><p>{{ __('Capture revenue and cost components for a complete order result.') }}</p></div><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div>
        <div class="primary-form profit-loss-form">
            <div class="profit-form-section"><div class="profit-section-title"><span><i class="fa-solid fa-chart-line"></i></span><div><h5>{{ __('Revenue Reference') }}</h5><p>{{ __('Select the order and enter its sales revenue.') }}</p></div></div><div class="row gy-3"><div class="col-md-6"><div class="form-group"><label class="form-label">{{ __('Order') }} <b>*</b></label><select class="form-control" name="order_id" required><option value="">{{ __('Select Order') }}</option>@foreach($orders as $order)<option value="{{ $order->id }}" @selected(old('order_id',$profitLoss?->order_id)==$order->id)>{{ $order->order_number }}</option>@endforeach</select></div></div><div class="col-md-6"><div class="form-group"><label class="form-label">{{ __('Sales Revenue') }} <b>*</b></label><input type="number" min="0" step="0.0001" class="form-control" name="sales_revenue" value="{{ old('sales_revenue',$profitLoss?->sales_revenue??0) }}" required></div></div></div></div>
            <div class="profit-form-section"><div class="profit-section-title"><span><i class="fa-solid fa-coins"></i></span><div><h5>{{ __('Cost Breakdown') }}</h5><p>{{ __('Enter all direct and indirect order costs.') }}</p></div></div><div class="row gy-3">@foreach(['material_cost'=>'Material Cost','production_cost'=>'Production Cost','salary_cost'=>'Salary Cost','overhead_cost'=>'Overhead Cost','other_cost'=>'Other Cost'] as $field=>$label)<div class="col-md-4"><div class="form-group"><label class="form-label">{{ __($label) }} <b>*</b></label><input type="number" min="0" step="0.0001" class="form-control" name="{{ $field }}" value="{{ old($field,$profitLoss?->{$field}??0) }}" required></div></div>@endforeach</div></div>
            <div class="profit-form-section"><div class="profit-section-title"><span><i class="fa-solid fa-flag-checkered"></i></span><div><h5>{{ __('Finalization') }}</h5><p>{{ __('Finalize the calculation when all costs are confirmed.') }}</p></div></div><div class="row gy-3"><div class="col-md-6"><div class="form-group"><label class="form-label">{{ __('Status') }} <b>*</b></label><select class="form-control" name="status" required>@foreach(garmentProfitLossStatuses() as $value=>$status)<option value="{{ $value }}" @selected(old('status',$profitLoss?->status??GARMENT_PROFIT_LOSS_STATUS_DRAFT)==$value)>{{ __($status[0]) }}</option>@endforeach</select></div></div><div class="col-12"><div class="form-group"><label class="form-label">{{ __('Notes') }}</label><textarea class="form-control" name="notes" rows="3">{{ old('notes',$profitLoss?->notes) }}</textarea></div></div></div></div>
        </div>
        <div class="btn-list mt-4 pt-3 border-top"><button type="button" class="primary-btn" data-bs-dismiss="modal">{{ __('Cancel') }}</button><button class="primary-btn" type="submit">{{ $profitLoss ? __('Update') : __('Save') }}</button></div>
    </div>
</form>
