@extends('auto_posts.admin.layouts.admin')
@push('title') {{ $title }} @endpush
@section('content')
<div class="section-title"><h2 class="title">{{ __($title) }}</h2><button type="button" class="primary-btn" data-bs-toggle="modal" data-bs-target="#add-cutting-modal"><i class="fa fa-plus me-2"></i>{{ __('Add Cutting Record') }}</button></div>
<div class="settings-page-area"><div class="settings-page-right"><div class="section-wrap"><div class="table-waraper"><div class="search-input-wrap mb-3"><label class="icon" for="cuttingSearchData"><i class="fa-solid fa-magnifying-glass"></i></label><input class="search-input" id="cuttingSearchData" placeholder="{{ __('Search order, style or marker...') }}"></div><input type="hidden" id="garment-cutting-data-route" value="{{ route('admin.garments.cutting.index') }}"><table class="display primary-table dataTable dtr-inline" id="garmentCuttingDataTable"><thead><tr><th class="keep-show">{{ __('SL') }}</th><th>{{ __('Order') }}</th><th>{{ __('Style') }}</th><th>{{ __('Cut Qty') }}</th><th>{{ __('Cutting Date') }}</th><th>{{ __('Status') }}</th><th class="keep-show">{{ __('Action') }}</th></tr></thead><tbody></tbody></table></div></div></div></div>
<div class="modal fade zModalTwo cutting-modal" id="add-cutting-modal" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable"><div class="modal-content zModalTwo-content">@include('admin.garments.cutting.form',['cutting'=>null,'orders'=>$orders,'materials'=>$materials])</div></div></div><div class="modal fade zModalTwo cutting-modal" id="edit-cutting-modal" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable"><div class="modal-content zModalTwo-content"></div></div></div>
@endsection
@push('style')<style>#add-cutting-modal .modal-dialog,#edit-cutting-modal .modal-dialog{max-width:960px;height:calc(100% - 2rem);min-height:0}#add-cutting-modal .modal-content,#edit-cutting-modal .modal-content{height:100%;max-height:100%;min-height:0;overflow:hidden}#add-cutting-modal form,#edit-cutting-modal form{display:flex;flex-direction:column;height:100%;min-height:0}#add-cutting-modal .modal-body,#edit-cutting-modal .modal-body{flex:1 1 auto;min-height:0;overflow-y:auto;padding:28px 30px 24px}.cutting-form-section{border:1px solid #eee8e5;border-radius:8px;padding:18px;background:#fff}.cutting-form-section+.cutting-form-section{margin-top:16px}.cutting-form-section-title{color:#1b1c17;font-size:15px;font-weight:600;margin:0 0 15px}.cutting-form-section-title i{color:#ff4f02;margin-right:8px}.cutting-modal .form-group{margin-bottom:0}.cutting-modal .form-control{min-height:44px}.cutting-modal-footer{display:flex;justify-content:flex-end;gap:10px;border-top:1px solid #eee8e5;margin-top:22px;padding-top:18px}</style>@endpush
@push('script')<script src="{{ asset('admin/js/garment-cutting.js') }}"></script>@endpush
