@extends('auto_posts.admin.layouts.admin')
@push('title') {{ $title }} @endpush
@section('content')
<div class="section-title"><h2 class="title">{{ __($title) }}</h2><button type="button" class="primary-btn" data-bs-toggle="modal" data-bs-target="#add-sewing-modal"><i class="fa fa-plus me-2"></i>{{ __('Add Production Record') }}</button></div>
<div class="settings-page-area"><div class="settings-page-right"><div class="section-wrap"><div class="table-waraper"><div class="search-input-wrap mb-3"><label class="icon" for="sewingSearchData"><i class="fa-solid fa-magnifying-glass"></i></label><input class="search-input" id="sewingSearchData" placeholder="{{ __('Search order, line or style...') }}"></div><input type="hidden" id="garment-sewing-data-route" value="{{ route('admin.garments.sewing.index') }}"><table class="display primary-table dataTable dtr-inline" id="garmentSewingDataTable"><thead><tr><th class="keep-show">{{ __('SL') }}</th><th>{{ __('Order') }}</th><th>{{ __('Style') }}</th><th>{{ __('Line') }}</th><th>{{ __('Output / Target') }}</th><th>{{ __('Date') }}</th><th>{{ __('Status') }}</th><th class="keep-show">{{ __('Action') }}</th></tr></thead><tbody></tbody></table></div></div></div></div>
<div class="modal fade zModalTwo sewing-modal" id="add-sewing-modal" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable"><div class="modal-content zModalTwo-content">@include('admin.garments.sewing.form',['production'=>null,'orders'=>$orders])</div></div></div><div class="modal fade zModalTwo sewing-modal" id="edit-sewing-modal" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable"><div class="modal-content zModalTwo-content"></div></div></div>
@endsection
@push('style')<style>#add-sewing-modal .modal-dialog,#edit-sewing-modal .modal-dialog{max-width:960px;height:calc(100% - 2rem);min-height:0}#add-sewing-modal .modal-content,#edit-sewing-modal .modal-content{height:100%;max-height:100%;min-height:0;overflow:hidden}#add-sewing-modal form,#edit-sewing-modal form{display:flex;flex-direction:column;height:100%;min-height:0}#add-sewing-modal .modal-body,#edit-sewing-modal .modal-body{flex:1 1 auto;min-height:0;overflow-y:auto;padding:28px 30px 24px}.sewing-form-section{border:1px solid #eee8e5;border-radius:8px;padding:18px;background:#fff}.sewing-form-section+.sewing-form-section{margin-top:16px}.sewing-form-section-title{color:#1b1c17;font-size:15px;font-weight:600;margin:0 0 15px}.sewing-form-section-title i{color:#ff4f02;margin-right:8px}.sewing-modal .form-group{margin-bottom:0}.sewing-modal .form-control{min-height:44px}.sewing-modal-footer{display:flex;justify-content:flex-end;gap:10px;border-top:1px solid #eee8e5;margin-top:22px;padding-top:18px}</style>@endpush
@push('script')<script src="{{ asset('admin/js/garment-sewing.js') }}"></script>@endpush
