<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?php echo e(__('Invoice')); ?> <?php echo e($invoice->invoice_number); ?></title>
    <style>
        *{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#263244;background:#f4f7fb;margin:0}.invoice-page{max-width:900px;margin:28px auto;background:#fff;padding:42px 48px;box-shadow:0 8px 30px rgba(15,23,42,.08)}.toolbar{display:flex;justify-content:flex-end;margin-bottom:20px}.toolbar button{border:0;border-radius:5px;background:#4778c7;color:#fff;padding:9px 16px;font-size:12px;cursor:pointer}.invoice-header{display:flex;justify-content:space-between;gap:30px;padding-bottom:25px;border-bottom:2px solid #4778c7}.invoice-brand h1{margin:0;color:#1b1c17;font-size:27px}.invoice-brand p{margin:7px 0 0;color:#64748b;font-size:12px}.invoice-meta{text-align:right}.invoice-meta h2{margin:0;color:#4778c7;font-size:21px}.invoice-meta p{margin:6px 0 0;color:#64748b;font-size:12px}.details{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin:28px 0}.detail-box{padding:15px 17px;border:1px solid #e5eaf0;border-radius:7px;background:#fbfcfe}.detail-box label{display:block;color:#8991a3;font-size:10px;text-transform:uppercase;letter-spacing:.05em;margin-bottom:7px}.detail-box strong{display:block;color:#1f2937;font-size:13px}.detail-box span{display:block;color:#64748b;font-size:12px;margin-top:4px}table{width:100%;border-collapse:collapse;margin-top:8px}th{background:#f1f5f9;color:#475569;text-align:left;font-size:10px;text-transform:uppercase;letter-spacing:.03em}th,td{border-bottom:1px solid #e5eaf0;padding:13px 10px;font-size:12px}td.amount,th.amount{text-align:right}.totals{width:310px;margin:22px 0 0 auto}.totals div{display:flex;justify-content:space-between;padding:7px 0;color:#64748b;font-size:12px}.totals .grand{border-top:2px solid #4778c7;margin-top:5px;padding-top:11px;color:#1b1c17;font-size:15px;font-weight:bold}.notes{margin-top:28px;padding:14px 16px;border-left:3px solid #4778c7;background:#f8fafc;color:#64748b;font-size:12px;line-height:1.6}.footer{margin-top:35px;padding-top:13px;border-top:1px solid #e5eaf0;color:#94a3b8;font-size:10px;text-align:center}@media(max-width:650px){.invoice-page{margin:0;padding:24px 18px;box-shadow:none}.invoice-header,.details{display:block}.invoice-meta{text-align:left;margin-top:18px}.detail-box{margin-bottom:10px}.totals{width:100%}}@media print{body{background:#fff}.invoice-page{max-width:none;margin:0;padding:18px;box-shadow:none}.toolbar{display:none}}
    </style>
</head>
<body>
    <main class="invoice-page">
        <div class="toolbar"><button onclick="window.print()">🖨 <?php echo e(__('Print Invoice')); ?></button></div>
        <header class="invoice-header"><div class="invoice-brand"><h1><?php echo e(getOption('app_name')); ?></h1><p><?php echo e(__('Commercial Invoice')); ?></p></div><div class="invoice-meta"><h2><?php echo e($invoice->invoice_number); ?></h2><p><?php echo e(__('Issue Date')); ?>: <?php echo e($invoice->issue_date?->format('d M Y') ?: '-'); ?></p><p><?php echo e(__('Due Date')); ?>: <?php echo e($invoice->due_date?->format('d M Y') ?: '-'); ?></p></div></header>
        <section class="details"><div class="detail-box"><label><?php echo e(__('Bill To')); ?></label><strong><?php echo e($invoice->order?->buyer?->company_name ?: '-'); ?></strong><span><?php echo e($invoice->order?->buyer?->email ?: ''); ?></span><span><?php echo e($invoice->order?->buyer?->phone ?: ''); ?></span></div><div class="detail-box"><label><?php echo e(__('Order Information')); ?></label><strong><?php echo e(__('Order')); ?>: <?php echo e($invoice->order?->order_number ?: '-'); ?></strong><span><?php echo e(__('Status')); ?>: <?php echo e(__(ucwords(str_replace('_',' ',$invoice->status)))); ?></span></div></section>
        <table><thead><tr><th><?php echo e(__('Description')); ?></th><th class="amount"><?php echo e(__('Amount')); ?></th></tr></thead><tbody><tr><td><?php echo e($invoice->order?->product_description ?: __('Garment order')); ?></td><td class="amount"><?php echo e($invoice->currency); ?> <?php echo e(number_format((float) $invoice->amount, 2)); ?></td></tr><tr><td><?php echo e(__('Tax')); ?></td><td class="amount"><?php echo e($invoice->currency); ?> <?php echo e(number_format((float) $invoice->tax_amount, 2)); ?></td></tr></tbody></table>
        <div class="totals"><div><span><?php echo e(__('Subtotal')); ?></span><strong><?php echo e($invoice->currency); ?> <?php echo e(number_format((float) $invoice->amount, 2)); ?></strong></div><div><span><?php echo e(__('Tax')); ?></span><strong><?php echo e($invoice->currency); ?> <?php echo e(number_format((float) $invoice->tax_amount, 2)); ?></strong></div><div class="grand"><span><?php echo e(__('Total')); ?></span><strong><?php echo e($invoice->currency); ?> <?php echo e(number_format((float) $invoice->total_amount, 2)); ?></strong></div><div><span><?php echo e(__('Paid')); ?></span><strong><?php echo e($invoice->currency); ?> <?php echo e(number_format((float) $invoice->paid_amount, 2)); ?></strong></div><div><span><?php echo e(__('Outstanding')); ?></span><strong><?php echo e($invoice->currency); ?> <?php echo e(number_format(max(0, (float) $invoice->total_amount - (float) $invoice->paid_amount), 2)); ?></strong></div></div>
        <?php if($invoice->notes): ?><div class="notes"><strong><?php echo e(__('Notes')); ?></strong><br><?php echo e($invoice->notes); ?></div><?php endif; ?>
        <div class="footer"><?php echo e(__('Thank you for your business.')); ?> · <?php echo e(getOption('app_name')); ?></div>
    </main>
</body>
</html>
<?php /**PATH C:\Users\ashik\ERP-Software\resources\views\admin\garments\invoices\print.blade.php ENDPATH**/ ?>