<?php $__env->startPush('title'); ?> 
    <?php echo e(__('2FA Verify')); ?> 
<?php $__env->stopPush(); ?>

<?php $__env->startSection('content'); ?>
    <div class="auth-area">
        <div class="auth-left">
            <div class="auth-form-wrap">
                <a href="<?php echo e(route('login')); ?>" class="brand-logo">
                    <img src="<?php echo e(getSettingImage('app_black_logo') ?: asset('assets/images/logo-dark.png')); ?>" alt="<?php echo e(getOption('app_name')); ?>">
                </a>
                <div class="auth-top">
                    <h2><?php echo e(__('2FA Authentication')); ?></h2>
                    <h3>
                        <?php echo e(__('Hello')); ?> <?php echo e(auth()->user()->name); ?>, <br />
                        <?php echo e(__('Enter the verification code generated by your mobile application (Google Authenticator)')); ?>

                    </h3>
                </div>
                <form action="<?php echo e(route('google2fa.authenticate.verify.action')); ?>" method="post">
                    <?php echo csrf_field(); ?>
                    <div class="auth-form">
                        <div class="form-group">
                            <label for="one_time_password" class="form-label"><?php echo e(__('Enter your authentication code')); ?></label>
                            <input type="text" required class="form-control" name="one_time_password" id="one_time_password"
                                placeholder="<?php echo e(__('Enter 6-digit code')); ?>" maxlength="6">
                            <?php $__errorArgs = ['one_time_password'];
$__bag = $errors->getBag($__errorArgs[1] ?? 'default');
if ($__bag->has($__errorArgs[0])) :
if (isset($message)) { $__messageOriginal = $message; }
$message = $__bag->first($__errorArgs[0]); ?>
                                <span class="text-danger fs-12"><?php echo e($message); ?></span>
                            <?php unset($message);
if (isset($__messageOriginal)) { $message = $__messageOriginal; }
endif;
unset($__errorArgs, $__bag); ?>
                        </div>
                        <button type="submit" class="auth-form-btn"><?php echo e(__('Next')); ?></button>
                    </div>
                </form>
                <p class="text-center fs-14 text-muted mt-3">
                    <?php echo e(__('If you lost your phone or uninstall the google authenticator app and enable to access your account please contact with us.')); ?>

                </p>
            </div>
        </div>
        <div class="auth-right">
            <img class="img-fluid" src="<?php echo e(getSettingImage('login_left_image') ?: asset('assets/images/auth-image.jpg')); ?>" alt="auth-image">
        </div>
    </div>
<?php $__env->stopSection(); ?>
<?php echo $__env->make('auth.layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\Users\ashik\ERP-Software\resources\views\auth\2fa-verify.blade.php ENDPATH**/ ?>