<div class="create-post-wrap">
    <div class="create-post-left">
        <div class="post-left-top">
            <ul class="post-latform-lsit">
                @foreach(SOCIAL_MEDIA_PLATFORMS as $platform)
                @php $platformLower = strtolower($platform); $isAllowed = isset($allowedProviders) ?
                in_array($platformLower, $allowedProviders) : true; @endphp
                <li>
                    <label class="platform-name{{ !$isAllowed ? ' disabled' : '' }}">
                        <input type="checkbox" class="platform-filter" value="{{ $platformLower }}"
                            data-platform="{{ $platformLower }}" data-allowed="{{ $isAllowed ? '1' : '0' }}"
                            {{ !$isAllowed ? ' disabled' : '' }}>
                        <span class="post-paltform"><span class="icon">
                                @switch($platform)
                                @case('Facebook')
                                <i class="fa-brands fa-facebook-f"></i>
                                @break
                                @case('LinkedIn')
                                <i class="fa-brands fa-linkedin-in"></i>
                                @break
                                @case('YouTube')
                                <i class="fa-brands fa-youtube"></i>
                                @break
                                @case('TikTok')
                                <i class="fa-brands fa-tiktok"></i>
                                @break
                                @case('Twitter')
                                <i class="fa-brands fa-x-twitter"></i>
                                @break
                                @case('Instagram')
                                <i class="fa-brands fa-instagram"></i>
                                @break
                                @case('Threads')
                                <i class="fa-brands fa-threads"></i>
                                @break
                                @default
                                <i class="fa-solid fa-globe"></i>
                                @endswitch
                            </span>{{ $platform }}</span>
                    </label>
                </li>
                @endforeach
            </ul>
        </div>
        <div class="post-left-bottom">
            <div class="search-input-wrap">
                <label class="icon" for="search">
                    <svg width="17" height="17" viewBox="0 0 17 17" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M10.625 10.625L11.6875 11.6875" stroke="#6E5858" stroke-width="1.5"
                            stroke-linecap="round" stroke-linejoin="round" />
                        <path
                            d="M11.9944 13.4762C11.5852 13.067 11.5852 12.4035 11.9944 11.9944C12.4035 11.5852 13.067 11.5852 13.4762 11.9944L14.9222 13.4405C15.3314 13.8497 15.3314 14.5131 14.9222 14.9222C14.5131 15.3314 13.8497 15.3314 13.4405 14.9222L11.9944 13.4762Z"
                            stroke="#6E5858" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                        <path
                            d="M11.6872 6.72982C11.6872 3.99141 9.46726 1.77148 6.72884 1.77148C3.99043 1.77148 1.77051 3.99141 1.77051 6.72982C1.77051 9.46824 3.99043 11.6882 6.72884 11.6882C9.46726 11.6882 11.6872 9.46824 11.6872 6.72982Z"
                            stroke="#6E5858" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                    </svg>
                </label>
                <input type="text" class="search-input" id="search" placeholder="{{ __('Search Accounts...') }}" />
            </div>
            <ul class="accounts-list">
                @foreach($accounts as $account)
                <li>
                    <label class="accounts-info">
                        <input class="form-check-input account-checkbox" type="checkbox" value="{{ $account->id }}"
                            data-platform="{{ strtolower($account->platform) }}">
                        {{ $account->username ?? $account->account_id }}
                    </label>
                </li>
                @endforeach
            </ul>

        </div>
    </div>
    <div class="create-post-center">
        <div class="post-center-top">
            <ul class="nav nav-tabs post-tabs" id="Post" role="tablist">
                <!-- Dynamic tabs will be generated by JavaScript based on selected platform -->
            </ul>
            <div class="post-content">
                <div id="emoji-picker-container" style="position: absolute; display: none; z-index: 1000;"></div>
                <textarea class="post-content-box" name="content" id="content"
                    placeholder="{{ __('Start from here...') }}">{{ old('content', isset($campaign) ? $campaign->content : '') }}</textarea>
            </div>
        </div>
        <div class="post-center-footer">
            <div class="post-footer-top">
                <div class="post-footer-left">
                    <ul class="post-actions">
                        <li class="dropdown">
                            <a href="#" data-bs-toggle="dropdown" role="button" aria-expanded="false">
                                <svg width="12" height="12" viewBox="0 0 12 12" fill="none"
                                    xmlns="http://www.w3.org/2000/svg">
                                    <path
                                        d="M11.73 6.7622H6.83102V11.7302H4.87602V6.7622H2.35513e-05V4.9912H4.87602V0.000201941H6.83102V4.9912H11.73V6.7622Z"
                                        fill="black" />
                                </svg>
                            </a>
                            <ul class="dropdown-menu media-dropdown">
                                <li>
                                    <a class="dropdown-item" href="#" data-bs-toggle="offcanvas"
                                        data-bs-target="#GalleryModal">
                                        <svg width="18" height="18" viewBox="0 0 18 18" fill="none"
                                            xmlns="http://www.w3.org/2000/svg">
                                            <rect x="2.25" y="2.25" width="13.5" height="13.5" rx="1.5"
                                                stroke="currentColor" stroke-width="1.5" />
                                            <circle cx="6.25" cy="6.25" r="1.25" fill="currentColor" />
                                            <path d="M15.75 11.25L12 7.5L6.75 12.75" stroke="currentColor"
                                                stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                                        </svg>
                                        {{ __('Open Gallery') }}
                                    </a>
                                </li>
                                <!-- <li>
                                    <a class="dropdown-item" href="#" id="uploadMediaBtn">
                                        <svg width="18" height="18" viewBox="0 0 18 18" fill="none"
                                            xmlns="http://www.w3.org/2000/svg">
                                            <path
                                                d="M15.75 11.25V14.25C15.75 15.0784 15.0784 15.75 14.25 15.75H3.75C2.92157 15.75 2.25 15.0784 2.25 14.25V11.25"
                                                stroke="currentColor" stroke-width="1.5" stroke-linecap="round" />
                                            <path d="M12.75 6L9 2.25L5.25 6" stroke="currentColor" stroke-width="1.5"
                                                stroke-linecap="round" stroke-linejoin="round" />
                                            <path d="M9 2.25V11.25" stroke="currentColor" stroke-width="1.5"
                                                stroke-linecap="round" />
                                        </svg>
                                        {{ __('Upload Media') }}
                                    </a>
                                    <input type="file" id="directMediaUpload" name="direct_media[]"
                                        accept="image/*,video/*" multiple style="display: none;">
                                </li> -->
                            </ul>
                        </li>
                        {{-- Emoji picker trigger --}}
                        <li>
                            <a href="#" id="emoji-trigger">
                                <svg width="18" height="18" viewBox="0 0 18 18" fill="none"
                                    xmlns="http://www.w3.org/2000/svg">
                                    <path
                                        d="M9 16.5C13.1421 16.5 16.5 13.1421 16.5 9C16.5 4.85786 13.1421 1.5 9 1.5C4.85786 1.5 1.5 4.85786 1.5 9C1.5 13.1421 4.85786 16.5 9 16.5Z"
                                        stroke="#141B34" stroke-width="1.5" stroke-linecap="round"
                                        stroke-linejoin="round" />
                                    <path
                                        d="M6 11.25C6.68409 12.1608 7.77322 12.75 9 12.75C10.2268 12.75 11.3159 12.1608 12 11.25"
                                        stroke="#141B34" stroke-width="1.5" stroke-linecap="round"
                                        stroke-linejoin="round" />
                                    <path d="M6.00673 6.75H6M12 6.75H11.9932" stroke="#141B34" stroke-width="1.5"
                                        stroke-linecap="round" stroke-linejoin="round" />
                                </svg>
                            </a>
                        </li>
                        {{-- Hashtag picker --}}
                        <li>
                            <a href="#" data-bs-toggle="modal" data-bs-target="#HashtagModal">
                                <svg width="18" height="18" viewBox="0 0 18 18" fill="none"
                                    xmlns="http://www.w3.org/2000/svg">
                                    <path d="M10.5 15.75L13.5 2.25" stroke="#141B34" stroke-width="1.5"
                                        stroke-linecap="round" stroke-linejoin="round" />
                                    <path d="M4.5 15.75L7.5 2.25" stroke="#141B34" stroke-width="1.5"
                                        stroke-linecap="round" stroke-linejoin="round" />
                                    <path d="M3.75 6H15.75" stroke="#141B34" stroke-width="1.5" stroke-linecap="round"
                                        stroke-linejoin="round" />
                                    <path d="M2.25 12H14.25" stroke="#141B34" stroke-width="1.5" stroke-linecap="round"
                                        stroke-linejoin="round" />
                                </svg>
                            </a>
                        </li>
                        {{-- Insert link trigger (opens InsertLinkModal) --}}
                        <li>
                            <a href="#" data-bs-toggle="modal" data-bs-target="#InsertLinkModal">
                                <svg width="18" height="18" viewBox="0 0 18 18" fill="none"
                                    xmlns="http://www.w3.org/2000/svg">
                                    <path
                                        d="M7.5 9.92175C7.6062 10.0957 7.73227 10.2603 7.87815 10.4121C8.78377 11.3546 10.1641 11.502 11.2182 10.8542C11.4135 10.7341 11.5975 10.5868 11.7654 10.4121L14.1949 7.88355C15.2683 6.76638 15.2683 4.95507 14.1949 3.83789C13.1215 2.7207 11.3811 2.72071 10.3076 3.83789L9.7725 4.39484"
                                        stroke="#141B34" stroke-width="1.5" stroke-linecap="round" />
                                    <path
                                        d="M8.22773 13.605L7.69238 14.1621C6.61895 15.2793 4.87853 15.2793 3.80509 14.1621C2.73164 13.0449 2.73164 11.2336 3.80509 10.1164L6.23465 7.5879C7.3081 6.4707 9.04853 6.4707 10.1219 7.5879C10.2678 7.73962 10.3938 7.90425 10.5 8.0781"
                                        stroke="#141B34" stroke-width="1.5" stroke-linecap="round" />
                                </svg>
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="post-footer-right">
                    <div class="btn-list mt-0">
                        <a href="javascript:void(0)" id="aiAssistantBtn" class="primary-btn btn-outline-secondary">
                            <svg width="17" height="17" viewBox="0 0 17 17" fill="none"
                                xmlns="http://www.w3.org/2000/svg">
                                <path
                                    d="M7.06229 3.9506L7.48888 5.13529C7.96276 6.45013 8.99816 7.48554 10.313 7.95941L11.4977 8.38601C11.6045 8.42479 11.6045 8.5762 11.4977 8.61445L10.313 9.04104C8.99816 9.51491 7.96276 10.5503 7.48888 11.8652L7.06229 13.0499C7.02351 13.1566 6.8721 13.1566 6.83385 13.0499L6.40726 11.8652C5.93338 10.5503 4.89798 9.51491 3.58313 9.04104L2.39845 8.61445C2.29166 8.57566 2.29166 8.42426 2.39845 8.38601L3.58313 7.95941C4.89798 7.48554 5.93338 6.45013 6.40726 5.13529L6.83385 3.9506C6.8721 3.84329 7.02351 3.84329 7.06229 3.9506Z"
                                    fill="#0D0D0D" />
                                <path
                                    d="M12.3948 1.10354L12.611 1.70332C12.8511 2.36898 13.3755 2.89332 14.0411 3.13345L14.6409 3.34966C14.6951 3.36932 14.6951 3.44582 14.6409 3.46548L14.0411 3.6817C13.3755 3.92182 12.8511 4.44616 12.611 5.11182L12.3948 5.7116C12.3751 5.76579 12.2986 5.76579 12.279 5.7116L12.0627 5.11182C11.8226 4.44616 11.2983 3.92182 10.6326 3.6817L10.0328 3.46548C9.97864 3.44582 9.97864 3.36932 10.0328 3.34966L10.6326 3.13345C11.2983 2.89332 11.8226 2.36898 12.0627 1.70332L12.279 1.10354C12.2986 1.04882 12.3756 1.04882 12.3948 1.10354Z"
                                    fill="#0D0D0D" />
                                <path
                                    d="M12.3948 11.2892L12.611 11.889C12.8511 12.5546 13.3755 13.079 14.0411 13.3191L14.6409 13.5353C14.6951 13.555 14.6951 13.6315 14.6409 13.6511L14.0411 13.8673C13.3755 14.1075 12.8511 14.6318 12.611 15.2975L12.3948 15.8972C12.3751 15.9514 12.2986 15.9514 12.279 15.8972L12.0627 15.2975C11.8226 14.6318 11.2983 14.1075 10.6326 13.8673L10.0328 13.6511C9.97864 13.6315 9.97864 13.555 10.0328 13.5353L10.6326 13.3191C11.2983 13.079 11.8226 12.5546 12.0627 11.889L12.279 11.2892C12.2986 11.235 12.3756 11.235 12.3948 11.2892Z"
                                    fill="#0D0D0D" />
                            </svg>
                            {{ __('AI Assistant') }}
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="create-post-right">
        <div class="tab-content" id="PostContent">
            <!-- Dynamic tab content will be generated by JavaScript based on selected platform -->
        </div>
    </div>
</div>