@extends('auth.layouts.app')

@push('title') 
    {{ __('2FA Verify') }} 
@endpush

@section('content')
    <div class="auth-area">
        <div class="auth-left">
            <div class="auth-form-wrap">
                <a href="{{ route('login') }}" class="brand-logo">
                    <img src="{{ getSettingImage('app_black_logo') ?: asset('assets/images/logo-dark.png') }}" alt="{{ getOption('app_name') }}">
                </a>
                <div class="auth-top">
                    <h2>{{ __('2FA Authentication') }}</h2>
                    <h3>
                        {{ __('Hello') }} {{ auth()->user()->name }}, <br />
                        {{ __('Enter the verification code generated by your mobile application (Google Authenticator)') }}
                    </h3>
                </div>
                <form action="{{ route('google2fa.authenticate.verify.action') }}" method="post">
                    @csrf
                    <div class="auth-form">
                        <div class="form-group">
                            <label for="one_time_password" class="form-label">{{ __('Enter your authentication code') }}</label>
                            <input type="text" required class="form-control" name="one_time_password" id="one_time_password"
                                placeholder="{{ __('Enter 6-digit code') }}" maxlength="6">
                            @error('one_time_password')
                                <span class="text-danger fs-12">{{ $message }}</span>
                            @enderror
                        </div>
                        <button type="submit" class="auth-form-btn">{{ __('Next') }}</button>
                    </div>
                </form>
                <p class="text-center fs-14 text-muted mt-3">
                    {{ __('If you lost your phone or uninstall the google authenticator app and enable to access your account please contact with us.') }}
                </p>
            </div>
        </div>
        <div class="auth-right">
            <img class="img-fluid" src="{{ getSettingImage('login_left_image') ?: asset('assets/images/auth-image.jpg') }}" alt="auth-image">
        </div>
    </div>
@endsection