@extends('auto_posts.admin.layouts.admin')
@push('title') {{ $title }} @endpush
@section('content')
<div class="garment-page" data-card-data-url="{{ route('admin.garments.merchandiser.insights.data') }}">
<div class="section-title"><h2 class="title">{{ __($title) }}</h2></div>
<div class="row g-3 mb-4">@foreach([['orderCount',$orderCount,'Assigned Orders','fa-list-check'],['overdueTasks',$overdueTasks,'Overdue Tasks','fa-calendar-xmark'],['deliveryRisk',$deliveryRisk,'Delivery Risk (7 Days)','fa-triangle-exclamation'],['buyerCount',$buyerCount,'Active Buyers','fa-users']] as $card)<div class="col-xl-3 col-md-6"><div class="section-wrap p-4" data-card-key="{{ $card[0] }}"><p class="text-muted mb-2">{{ __($card[2]) }}</p><h3 data-card-value>{{ number_format($card[1]) }}</h3><i class="fa-solid {{ $card[3] }} text-primary"></i></div></div>@endforeach</div>
<div class="row g-4"><div class="col-xl-6"><div class="section-wrap p-4"><h4 class="mb-3">{{ __('Order Handover') }}</h4><form method="post" action="{{ route('admin.garments.merchandiser.handover') }}">@csrf<select name="order_id" class="form-control mb-2" required><option value="">{{ __('Select Order') }}</option>@foreach($orders as $order)<option value="{{ $order->id }}">{{ $order->order_number }} - {{ $order->buyer?->company_name }}</option>@endforeach</select><select name="to_user_id" class="form-control mb-2" required><option value="">{{ __('New Merchandiser') }}</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }}</option>@endforeach</select><textarea name="notes" class="form-control mb-2" placeholder="{{ __('Handover notes') }}" required></textarea><button class="primary-btn">{{ __('Hand Over Order') }}</button></form></div></div><div class="col-xl-6"><div class="section-wrap p-4"><h4 class="mb-3">{{ __('Handover History') }}</h4>@forelse($handovers as $handover)<div class="border-bottom py-2"><strong>{{ $handover->order?->order_number }}</strong><p class="mb-0 small">{{ $handover->fromUser?->name }} → {{ $handover->toUser?->name }}</p><span class="text-muted small">{{ $handover->handed_over_at?->format('d M Y, h:i A') }}</span></div>@empty<p class="text-muted">{{ __('No handover records') }}</p>@endforelse</div></div></div>
<button type="button" class="mt-2" data-card-retry hidden>{{ __('Retry loading metrics') }}</button>
</div>
@endsection
