@extends('auto_posts.admin.layouts.admin')
@push('title') {{ $title }} @endpush
@section('content')
<div class="section-title"><h2 class="title">{{ __($title) }}</h2><button class="primary-btn" data-bs-toggle="modal" data-bs-target="#add-incentive-modal"><i class="fa fa-plus me-2"></i>{{ __('Add Incentive') }}</button></div>
<div class="settings-page-area"><div class="settings-page-right"><div class="section-wrap"><div class="table-waraper"><input type="hidden" id="incentive-route" value="{{ route('admin.garments.incentives.index') }}"><table class="display primary-table dataTable dtr-inline" id="garmentIncentiveDataTable"><thead><tr><th class="keep-show">SL</th><th>Worker</th><th>Order</th><th>Operation</th><th>Qty</th><th>Amount</th><th>Status</th><th class="keep-show">Action</th></tr></thead><tbody></tbody></table></div></div></div></div>
<div class="modal fade zModalTwo" id="add-incentive-modal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable"><div class="modal-content zModalTwo-content">@include('admin.garments.incentives.form',['incentive'=>null,'orders'=>$orders])</div></div></div><div class="modal fade zModalTwo" id="edit-incentive-modal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content zModalTwo-content"></div></div></div>
@endsection
@push('style')<style>
#add-incentive-modal .modal-dialog,#edit-incentive-modal .modal-dialog{max-width:720px}.modal-form-header{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:20px}.modal-form-header h4{font-size:20px;font-weight:500;line-height:28px;color:#1b1c17;margin:0 0 4px}.modal-form-header p{font-size:13px;color:#808080;margin:0}.incentive-form-section{border:0;border-bottom:1px solid #eee8e5;border-radius:0;background:transparent;padding:0 0 18px}.incentive-form-section+.incentive-form-section{margin-top:18px}.incentive-section-title{display:flex;align-items:center;gap:10px;margin-bottom:14px}.incentive-section-title>span{width:32px;height:32px;display:inline-flex;align-items:center;justify-content:center;border-radius:7px;color:#ff4f02;background:#fff2ec}.incentive-section-title h5{font-size:14px;font-weight:600;color:#1b1c17;margin:0 0 2px}.incentive-section-title p{font-size:12px;color:#808080;margin:0}.incentive-form .form-control{min-height:42px}
</style>@endpush
@push('script')<script>$(function(){var t=$('#garmentIncentiveDataTable').DataTable({pageLength:10,ordering:false,serverSide:true,processing:true,responsive:true,dom:'t',ajax:$('#incentive-route').val(),columns:[{data:'sl'},{data:'employee_name'},{data:'order_number'},{data:'operation'},{data:'production_quantity'},{data:'amount_display'},{data:'status'},{data:'action'}],columnDefs:[{targets:'keep-show',className:'all'}]});});</script>@endpush
